modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
modId="blockswapper"
version="1.0"
displayName="Block Swapper"
credits="Credit goes to Abu's horrible house and my urge to swap it."
displayURL="https://www.curseforge.com/minecraft/mc-mods/more-paths-repathed"
authors="Kuraion"
logoFile="logo.png"
description='''Adds a new tool type that lets you swap placed blocks with items in your offhand.'''

[[dependencies.blockswapper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="BOTH"
